services:
  redis:
    image: redis:7.2.5
    container_name: liedjesuitnederland-redis
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    restart: always
    volumes:
      - ./dаta:/root/redis
    env_file: .env.local
  mysql:
    image: mysql:8.0.37
    container_name: liedjesuitnederland-database
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      liedjesuitnederland:

volumes:
  mysqldata:
    driver: local

networks:
  liedjesuitnederland:
    ipam:
      driver: default
