services:
  mysql:
    image: mysql:8.0.37
    container_name: liedjesuitnederland-database
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      liedjesuitnederland:

volumes:
  mysqldata:
    driver: local

networks:
  liedjesuitnederland:
    ipam:
      driver: default
