services:
  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    image: harrydeboer/liedjesuitnederland.nl:latest
    working_dir: /var/www/html
    container_name: liedjesuitnederland
    ports:
      - "80:80"
      - "443:443"
    networks:
      liedjesuitnederland:
    depends_on:
      - database
  database:
    image: mysql:8.0.37
    container_name: liedjesuitnederlandDb
    env_file: .env.local
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      liedjesuitnederland:

volumes:
  mysqldata:
    driver: local

networks:
  liedjesuitnederland:
    ipam:
      driver: default
